blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.byzanlink.io/byzanlink-byzanlink-bundler-bundler/byzanlink-bundler
    about: For more detailed guide follow our docs
  - name: Join our Discord community
    url: https://discord.byzanlink.io
    about: Participate in our thriving community of contributors, users, and supporters.
